services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=070702
      - MYSQL_DATABASE=appdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build:
      context: ./FirstWebApplication
      dockerfile: Dockerfile
    image: firstwebapplication:dev
    container_name: firstwebappcontainer
    depends_on:
      - mariadb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mariadb;port=3306;database=appdb;user=root;password=070702;SslMode=None
    ports:
      - "5000:8080"

volumes:
  mariadb_data:
